# Generated by Django 4.2.5 on 2024-04-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efitterbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylegurupersona',
            name='link',
            field=models.CharField(default='n/a', max_length=500),
        ),
    ]
