# Generated by Django 4.2.5 on 2024-04-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efitterbackend', '0003_alter_stylegurupersona_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomposition',
            old_name='composition_type',
            new_name='type',
        ),
    ]
